// Generated by CoffeeScript 1.12.3
(function() {
  var RequestHandler, Router, Server, handler, router, server;

  Server = require('./server');

  Router = require('./router');

  RequestHandler = require('./request_handler');

  handler = new RequestHandler();

  router = new Router({
    handler: handler
  });

  server = new Server({
    router: router
  });

  server.start();

}).call(this);
